### ISSUE TITLE
Creating ColumnFamily and Column through C++ code

### ISSUE THREAD

**Issue by durgadevi4887** [posulliv/libcassandra#10]
Hi,
          We want to create  ColumnFamily and Column dynamically in cassandra database through the C++ Code.Is the posulliv libcassandra c++ client support to dynamically create ColumnFamily?Can you please explain how to create columnfamily in cassandra through C++ code?

**Comment by posulliv** [comment]
Latest updates to libcassandra allows you to do this. For example, to create a keyspace and column family, you could do:

   /\* create keyspace */
    KeyspaceDefinition ks_def;
    ks_def.setName("drizzle");
    client->createKeyspace(ks_def);
    client->setKeyspace(ks_def.getName());

```
/* create standard column family */
ColumnFamilyDefinition cf_def;
cf_def.setName("Data");
cf_def.setKeyspaceName(ks_def.getName());
client->createColumnFamily(cf_def);
```

**Comment by durgadevi4887** [comment]
Thanks.
      It is helpful to create keyspace and ColumnFamily dynamically.Likewise is it possible to create column and their type dynamically through libcassandra.
