### ISSUE TITLE
Creating Column and their datatype dynamically in libcassandra

### ISSUE THREAD

**Issue by durgadevi4887** [posulliv/libcassandra#12]
Using libcassanrda237fc57 we can create Keyspace and columnFamily dynamically.Likewise we have to create column and their datatype dynamically.Is it possible to create column and their type dynamically.

**Comment by posulliv** [comment]
This is now possible with the ColumnDefinition class. Create a ColumnDefinition corresponding to the column you want to create and then add it to a ColumnFamilyDefinition object before creating a column family.

For example:

ColumnDefinition col_def;
col_def.setName("my_col");
col_def.setValidationClass("LongType");

col_family_def.addColumnMetadata(col_def);
