### ISSUE TITLE
Compilation Issue on Mac OSX

### ISSUE THREAD

**Issue by jahluwalia** [posulliv/libcassandra#13]
1. On osx for libcassandra, you have to had this flag when configuring: ./configure CXXFLAGS="-I/opt/local/include -Wno-variadic-macros"
2. had to add #include<sys/time.h> to util_functions.cc. I have to fill out a bug report for libassandra i guess.

**Comment by posulliv** [comment]
I pushed a fix for the OSX compilation failure related to the missing include.

For the variadic macros, I'm going to just mentioned the -Wno-variadic-macros flag must be used on that platform.
