### ISSUE TITLE
TException : No more data to read.

### ISSUE THREAD

**Issue by xxjjs** [posulliv/libcassandra#18]
Environment: Cassandra 0.7.4  Thrift 0.5 Ubuntu

I could create the keyspace and column family thru command lines. And not problem to insert and get columns.

Then I installed thrift and try to use c++ to access cassandra. 
Finally the test code compiled and linked.
But as soon as I try to call cassandra function, I got exceptions. I try to search in the web, but looks like there are not many documents available.

Any thing I did wrong? Thanks.

The source is simple, I posted below :

// remove #include , those lines make the post ugly 

using namespace std;
using namespace apache::thrift;
using namespace apache::thrift::protocol;
using namespace apache::thrift::transport;
using namespace org::apache::cassandra;
using namespace boost;

static string host("localhost");
static int port= 9160;

int main()
{
    shared_ptr<TTransport> socket(new TSocket(host, port)); 
    shared_ptr<TTransport> transport(new TBufferedTransport(socket));
    shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
    CassandraClient client(protocol);

```
try
{

//Open transport
transport->open();

string keyspace = "cpptest";
```

********\*    client.set_keyspace(keyspace);
 // Get exception on above line

```
string columnFamily = "Users";
ColumnParent parent;
parent.column_family.assign(columnFamily);
parent.super_column.assign("");


Column col;
col.name.assign("name");
col.value.assign("Bill Gates");
col.timestamp = 111111;

client.insert("bGates", // key
        parent, // &ColumnParent
        col,    // &Column
        ConsistencyLevel::ONE); // consistency level

ColumnOrSuperColumn ret_val;
ColumnPath  path;
path.column_family.assign(columnFamily);
path.super_column.assign("");
path.column.assign("name");

client.get(ret_val,     // &ColumnOrSuperColumn return value
     "bGates",  // key
     path,      // column path
     ConsistencyLevel::ONE);    // consistency level

printf("Column name retrieved is: %s\n", ret_val.column.name.c_str());
printf("Value in column retrieved is: %s\n", ret_val.column.value.c_str());

transport->close();
}

catch (InvalidRequestException &re)
{
    printf("InvalidRequestException : ");
    printf("ERROR: %s\n", re.why.c_str());
}
catch (TException &tx)
{
    printf("TException : ");
    printf("ERROR: %s\n", tx.what());
}
```

}

////////////////////////////////////////////////////
Here is the keyspace describtion:

[default@cpptest] describe keyspace cpptest;
Keyspace: cpptest:
  Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
    Replication Factor: 1
  Column Families:
    ColumnFamily: Users
      Columns sorted by: org.apache.cassandra.db.marshal.UTF8Type
      Row cache size / save period: 0.0/0
      Key cache size / save period: 200000.0/14400
      Memtable thresholds: 0.140625/30/1440
      GC grace seconds: 864000
      Compaction min/max thresholds: 4/32
      Read repair chance: 1.0
      Built indexes: []

**Comment by minaguib** [comment]
Are you actually using libcassandra ?

It looks to be like you're using the thrift-cpp interface directly without using libcassandra at all.

libcassandra is typically consumed by using the CassandraFactory which returns a Cassandra instances.

If you're using libcassandra, start by compiling the included examples/simple.cc file and see if that succeeds.

**Comment by xxjjs** [comment]
Thanks. Finally I got it run on my box.
I might miss some step when　Ｉ　ｉｎｓｔａｌｌ　ｌｉｂｃａｓｓａｎｄｒａ　ａｎｄ　ｔｈｒｉｆｔ．　Ｉ　ｊｕｓｔ　ｒｅ－ｉｎｓｔａｌｌ　ｔｈｅｍ　ａｎｄ　ｆｏｌｌｏｗ　ｔｈｅ　ｒｅａｄｍｅ　ｃａｒｅｆｕｌｌｙ．　Ｎｏｗ　ｉｔ　ｓｕｃｃｅｅｄ　ｒｕｎｎｉｎｇ　ｏｎ　ｍｙ　ｂｏｘ．
