### ISSUE TITLE
surprised by the signature for Keyspace::insertSuperColumn()...

### ISSUE THREAD

**Issue by bmpercy** [posulliv/libcassandra#2]
would've thought:
- you'd accept a super column name somewhere
- and then either a column name or a map of column names to values

haven't tried calling this function yet (just getting started here), but was trying to figure out how everything worked, so if it does work, i'll still want to know the answer to above. ;)

  /**
     \* Insert a super column
     *
     \* @param[in] key the column key
     \* @param[in] column_family the column family
     \* @param[in] column_name the column name
     \* @param[in] value the column value
     */
    void insertSuperColumn(const std::string &key,
                           const std::string &column_family,
                           const std::string &column_name,
                           const std::string &value);

thanks,
bp

**Comment by posulliv** [comment]
First off, I'm really really sorry for the delayed response. I had my master's thesis defense this morning so have been unable to any interesting work in the last few weeks ;)

To answer your question, the column_name parameter actually is the super_column_name. The insert functions such as insertColumn and insertSuperColumn are just wrappers around the thrift API. In the thrift API documented on the Cassandra wiki:

http://wiki.apache.org/cassandra/API

You will see the insert function takes a ColumnPath parameter. In a perfect world, we would not need a separate method for inserting a super column or inserting a regular column. The reason for this is the horrible thrift API that we are wrapping. If you look at the source for both insert functions in the keyspace.cc file you will that there is only 1 line that is different. 

I'm not sure if that answers your question fully or not but feel free to ask more and I'll make sure to answer them in a more timely manner this time :)

**Comment by minaguib** [comment]
Hi Padraig

Something is confusing me about this same issue as well.

If you compare the cassandra-cli set command for a regular column:
    cassandra> set Keyspace1.Standard2['joe']['age'] = '20'

It equivalent to this libcassandra call:
    insertColumn("joe", "Standard2", "age", "20")

However, consider the cassandra-cli command which sets in a supercolumn:
    cassandra> set Keyspace1.Super2['joe']['friends']['bob'] = 'Happy'

I'm confused as to how this would be when using libcassandra's insertSuperColumn

Inspecting the code,  I _think_ the method is missing a super_column_name in its signature, and then something like col_path.super_column.assign(super_column_name)

Or perhaps I'm missing something (perhaps column_name is combined with a delimiter ?)...

**Comment by minaguib** [comment]
Discussed on IRC / Padraig agrees with the above / Will fix + send pull request.

**Comment by posulliv** [comment]
Do you mind me asking what you would like to see? To be honest, I don't work with super-columns so its hard for me to comment on the super column API. Hopefully, minaguib can add some insight on your issue.

One thing I'm thinking of doing is adding an insert method that exposes the lower level ColumnPath object so that the insert API would be:

  insert(const std::string &key,
           const org::apache::cassandra::ColumnPath &column_path,
           const std::string &value);

This is how the Java client Hector handles insert.

Doing it this way would remove the confusion and make the API much simpler to maintain but might make it a bit harder on the user.

**Comment by bmpercy** [comment]
minaguib's API change makes sense to me. that's the kind of change i was thinking you'd need....just wasn't sure how you were expecting the supercolumn and column names to be squished into a single string argument in the old form. :) thanks, you two!
