### ISSUE TITLE
Bug in removing super column

### ISSUE THREAD

**Issue by fduan** [posulliv/libcassandra#4]
col_path.column.assign(super_column_name);

should be:

col_path.super_column.assign(super_column_name);

void Keyspace::remove(const string &key,
                      const string &column_family,
                      const string &super_column_name,
                      const string &column_name)
{
  ColumnPath col_path;
  col_path.column_family.assign(column_family);
  if (! super_column_name.empty())
  {
    col_path.column.assign(super_column_name);
    col_path.__isset.super_column= true;
  }
  if (! column_name.empty())
  {
    col_path.column.assign(column_name);
    col_path.__isset.column= true;
  }
  remove(key, col_path);
}

**Comment by fduan** [comment]
Can you guys confirm?

**Comment by themanatuf** [comment]
I second this. Making the proposed change in my local instance solves the problem. Failing to do so causes a "Default TException" to be thrown because no SuperColumn is being set properly.

**Comment by posulliv** [comment]
Thanks, this fix has been applied in the 0.6.5 branch now.
